### ISSUE TITLE
Master file not being autmatically recognised

### ISSUE THREAD

**Issue by kirk86** [mattfidler/guess-tex-master.el#1]
Hi, thanks for posting this snippet.
If you don't mind me asking, how is this supposed to work.
I see that the guess* functions are autoloaded and hooked into the different latex modes but when I have the following structure
```
main.tex
new.tex
```
Where main.tex is the main file which includes the local variables indicating that it is the master file.
Now, when I create the new file the default behaviour of AUCTeX if I'm not mistaken is to ask the user  to indicate  the master file, having your snippet in my configs folder when I create the new.tex I am no longer being prompted to indicate the master file.

Shouldn't I be prompted to confirm the guessed master file after all since guess-master* functions should be guessing which is the correct master file?

**Comment by mattfidler** [comment]
I think this was just guessing based on if the master included things with the "\include".  

I haven't used it for many years, so I am unsrue.
